team:
   name: Proyecto equipo 13
   members:
      - user: ma.munozb1@uniandes.edu.co
        percentage: 25
      - user: h.maury@uniandes.edu.co
        percentage: 25
      - user: f.alarconf@uniandes.edu.co
        percentage: 25
      - user: js.bohorquezg1@uniandes.edu.co
        percentage: 25
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/152/views/1
user-management:
  folder: users
  port: 3000
  authors:
    - h.maury@uniandes.edu.co
post-management:
  folder: posts
  port: 3001
  authors: 
    - js.bohorquezg1@uniandes.edu.co
offer-management:
  folder: offers
  port: 3003
  authors:
    - f.alarconf@uniandes.edu.co
route-management:
  folder: routes
  port: 3002
  authors:
    - ma.munozb1@uniandes.edu.co