version: "1.0"
   
services:
  api_offer:
    container_name: api_offer
    image: api_offer
    restart: always
    build: ./offers/
    ports:
      - "3003:3003"
    volumes:
      - /usr/src/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=offer_db
      - DB_PORT=5432
      - DB_NAME=offer_db
    depends_on:
      - offer_db
    networks:
      - offer_net
      - app_net
    links:
      - offer_db

  offer_db:
    container_name: offer_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=offer_db
    ports:
      - "5432:5432"
    networks:
      - offer_net
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

networks:
  offer_net:
    driver: bridge
  app_net:
    driver: bridge
