version: "1.0"
   
services:
  route_db:
    container_name: route_db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=route_db
    ports:
      - "5432:5432"
    networks:
      - route_net
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

networks:
  route_net:
    driver: bridge
